es_name: "Sep_CMA_ES"
problem_type: "brax"
env_name: "ant"
normalize: true
es_config:
  pop_size: 1024
  elite_ratio: 0.5
  init_stdev: 0.1
num_tests: 128
n_repeats: 16
max_iter: 300
test_interval: 100
log_interval: 20
seed: 42
gpu_id: [0, 1, 2, 3]
debug: false