es_name: "Sep_CMA_ES"
problem_type: "waterworld_ma"
normalize: false
es_config:
  pop_size: 16
  elite_ratio: 0.5
  init_stdev: 0.065
hidden_size: 100
num_tests: 16
n_repeats: 64
max_iter: 2000
test_interval: 100
log_interval: 10
seed: 42
gpu_id: 0
debug: false