es_name: "PGPE"
problem_type: "brax"
env_name: "ant"
normalize: true
es_config:
  pop_size: 128
  center_learning_rate: 0.01
  stdev_learning_rate: 0.07
  init_stdev: 0.04
  optimizer: "adam"
hidden_size: 64
num_tests: 1
n_repeats: 1
max_iter: 1
test_interval: 1
log_interval: 1
seed: 42
gpu_id: [0, 1, 2, 3]
debug: false