es_name: "iAMaLGaM"
problem_type: "waterworld"
normalize: false
es_config:
  full_covariance: false
  elite_ratio: 0.35
  pop_size: 256
  init_stdev: 0.0
  decay_stdev: 0.999
  limit_stdev: 0.0
hidden_size: 100
num_tests: 100
n_repeats: 32
max_iter: 1000
test_interval: 50
log_interval: 10
seed: 42
gpu_id: [0, 1, 2, 3]
debug: false